config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :games
  resources :parties
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :parties
  belongs_to :user
end

app/models/party.rb
class Party < ApplicationRecord
  has_many :solutions
  belongs_to :user
end

app/models/solution.rb
class Solution < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :games
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def new
    @game = Game.new
  end

  def create
    @game = Game.new(score: 0, best_game: 0)
    @game.user = current_user
    @game.save
    @count = 1
    if current_user.total_games.nil?
      current_user.total_games = 1
    else
      current_user.total_games += 1
    end
    current_user.save
    redirect_to root_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @party = Party.new
  end
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  before_action :new_list
  def new
    @party = Party.new
    raise
  end

  def create
    @party = Party.new(ten_letters_list: @ten_letters_list, word: params[:word] )
    @party.save
    raise
  end

  def new_list
    array = ('A'..'Z').to_a
    array_vowels = ["A","E","I","O","U","Y"]
    array_cons = array.reject { |letter| array_vowels.include?(letter) }
    @ten_letters_list = array_vowels.sample(5)
    @ten_letters_list + array_cons.sample(5)
  end

  private

  def party_params
    params.require(:party).permit(:ten_letters_list, :word, :available)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Test_TA</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>
<%= render "shared/flashes" %>

app/views/pages/home.html.erb
<h1>Welcome to the longest word game</h1>
<h2>Total game played : <%= current_user.total_games %></h2>
<ul>
prout
  <% if @party.nil? %>
  <% else %>
    <%= @party.ten_letters_list %>
  <% end %>
prout
</ul>
<%= simple_form_for [@party] do |f| %>
<p><%= f.input :word, label: "your answer"%></p>
<p><%= f.submit "play", class: "button-17" %></p>
<% end %>
<%= link_to "Start a new game", games_path, data: { turbo_method: "post"}, class: "btn btn-primary" %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>